services:

  postgres-db:
    image: postgres:13.22-trixie
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser # default=postgres
      POSTGRES_PASSWORD: 1qazZAQ!2wsxXSW@
    ports:
      - "5432:5432" # This opens port 5432 on your actual computer